version: '3.8'

services:
  library-api:
    build:
      context: .
      dockerfile: Library-Api/Dockerfile
    ports:
      - "7283:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=BookLibrary;uid=root;pwd=Cavalo153@;
      - Redis__Host=redis
      - Redis__Port=6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cavalo153@
      MYSQL_DATABASE: BookLibrary
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
